### get all

GET localhost:3001/api/notes

### get one

GET localhost:3001/api/notes/6abf2af4760bc7c1d463045a

### delete one

DELETE localhost:3001/api/notes/1

### create one

POST localhost:3001/api/notes
Content-Type: application/json

{
  "content": "test create"
  }
